version: '3.1'

services:
  db:
    image: postgres
    #restart: always
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
